-- .schema
-- CREATE TABLE users (
--     user_id TEXT PRIMARY KEY,
--     user_name TEXT NOT NULL,
--     user_contact TEXT,
--     user_book TEXT
-- );

-- CREATE TABLE  books (
--                     book_id TEXT PRIMARY KEY,
--                     book_title TEXT,
--                     book_genre TEXT,
--                     book_author TEXT,
--                        book_status TEXT
--                     );
-- DELETE FROM books WHERE book_id = "er"; 